name: Setup RNA Motif Library

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: 3.8
          activate-environment: rna_motif_env
          auto-activate-base: false

      - name: Install the RNA Motif Library
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate rna_motif_env
          pip install .

      - name: Verify installation
        run: |
          source ~/miniconda3/etc/profile.d/conda.sh
          conda activate rna_motif_env
          python -m pip list
