name: Setup RNA Motif Library

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          python-version: 3.8
          activate-environment: rna_motif_env
          auto-activate-base: false

      - name: Install the RNA Motif Library
        run: |
          conda run -n rna_motif_env pip install .

      - name: Verify installation
        run: |
          conda run -n rna_motif_env python -m pip list

      - name: Download CIFs
        shell: bash -l {0}
        run: |
          conda activate rna_motif_env
          python rna_motif_library/cli.py download_cifs --threads 8
