name: Setup RNA Motif Library

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
          activate-environment: rna_motif_env
          auto-activate-base: false

      - name: Clone the RNA Motif Library repository
        run: |
          git clone https://github.com/YesselmanLab/rna_motif_library.git
          cd rna_motif_library

      - name: Install the RNA Motif Library
        run: |
          pip install .

      - name: Verify installation
        run: |
          python -m pip list
